#ifndef MAPPER_HPP
#define MAPPER_HPP

#include "../Tokens.hpp"
#include <unordered_map>
#include <string>

std::unordered_map<std::string, int> terminalToToken {
   {"int", TOKEN_INT},
   {"float", TOKEN_FLOAT},
   {"string", TOKEN_STRING},
   {"bool", TOKEN_BOOL},
   {"program", TOKEN_PROGRAM},
   {"procedure", TOKEN_PROCEDURE},
   {"begin", TOKEN_BEGIN},
   {"end", TOKEN_END},
   {"var", TOKEN_VAR},
   {"in", TOKEN_IN},
   {"struct", TOKEN_STRUCT},
   {"not", TOKEN_NOT},
   {"null", TOKEN_NULL},
   {"new", TOKEN_NEW},
   {"ref", TOKEN_REF},
   {"deref", TOKEN_DEREF},
   {"true", TOKEN_TRUE},
   {"false", TOKEN_FALSE},
   {"if", TOKEN_IF},
   {"then", TOKEN_THEN},
   {"else", TOKEN_ELSE},
   {"fi", TOKEN_FI},
   {"while", TOKEN_WHILE},
   {"do", TOKEN_DO},
   {"od", TOKEN_OD},
   {"return", TOKEN_RETURN},
   {"enum", TOKEN_ENUM},
   {"of", TOKEN_OF},
   {"&&", TOKEN_AND},
   {"||", TOKEN_OR},
   {"<", TOKEN_COMP},
   {"<=", TOKEN_COMP},
   {">", TOKEN_COMP},
   {">=", TOKEN_COMP},
   {"=", TOKEN_COMP},
   {"<>", TOKEN_COMP},
   {"+", TOKEN_ADD},
   {"-", TOKEN_SUB},
   {"*", TOKEN_MULT},
   {"/", TOKEN_DIV},
   {"^", TOKEN_POT},
   {":=", TOKEN_ATTRIBUTION},
   {"", },
   {"", },
   {"", },
   {"", },
   {"", },
   {"", },
   {"", },
   {"", },
   {"", },
   {"", },
   {"", },
};

#endif // MAPPER_HPP