%option c++
%option warn debug
%option yyclass="Scanner"
%option case-insensitive
%option noyywrap nounput noinput nodefault

%top{
#include <cstdint>
}

%{
#include "scanner.hpp"
#include "parser.hpp"

#define YY_USER_ACTION  loc.columns(YYLeng());
%}

DIGIT     [0-9]
LETTER    [a-zA-Z]

%s BTWMODE

%%

\r\n|\r|\n|\n\r { loc.lines(1); loc.step(); }
[ \t]          { loc.step(); }

"+"            { return yy::Parser::make_ADD(loc); }
"-"            { return yy::Parser::make_MINUS(loc); }
"*"            { return yy::Parser::make_MULT(loc); }
"/"            { return yy::Parser::make_DIV(loc); }
"^"            { return yy::Parser::make_POT(loc); }
"("            { return yy::Parser::make_OP(loc); }
")"            { return yy::Parser::make_CP(loc); }

{LETTER}((({LETTER}|{DIGIT}|_)*_({LETTER}|{DIGIT})+)|({LETTER}|{DIGIT})*) {
    return yy::Parser::make_NAME(YYText(), loc);
}

.              { return yy::Parser::make_YYUNDEF(loc); }
<<EOF>>        { return yy::Parser::make_YYEOF(loc); }

%%
