%{
#include <iostream>
#include "Tokens.hpp"

int yylex(void);
void yyerror(char const* s);
%}

/// TOKENS
%token TOKEN_INT TOKEN_FLOAT TOKEN_STRING TOKEN_BOOL TOKEN_PROGRAM TOKEN_PROCEDURE
%token TOKEN_BEGIN TOKEN_END TOKEN_VAR TOKEN_IN TOKEN_STRUCT TOKEN_NOT TOKEN_NULL
%token TOKEN_NEW TOKEN_REF TOKEN_DEREF TOKEN_TRUE TOKEN_FALSE TOKEN_IF TOKEN_THEN
%token TOKEN_ELSE TOKEN_FI TOKEN_WHILE TOKEN_DO TOKEN_OD TOKEN_RETURN TOKEN_ENUM
%token TOKEN_OF TOKEN_AND TOKEN_OR TOKEN_COMP TOKEN_ADD TOKEN_SUB TOKEN_MULT
%token TOKEN_DIV TOKEN_POT TOKEN_ATTRIBUTION TOKEN_COLON TOKEN_OPEN_PARENTHESIS
%token TOKEN_CLOSE_PARENTHESIS TOKEN_SEMICOLON TOKEN_COMMA TOKEN_DOT TOKEN_OPEN_BRACES
%token TOKEN_CLOSE_BRACES TOKEN_SINGLE_LINE_COMMENT TOKEN_MULTIPLE_LINE_COMMENT
%token NAME INT_LITERAL FLOAT_LITERAL STRING_LITERAL TOKEN_ERRO TOKEN_EQUAL
%token TOKEN_CIPHER TOKEN_EPSILON

/// PRECEDÊNCIA
%left TOKEN_OR
%left TOKEN_AND
%right TOKEN_NOT
%left TOKEN_COMP TOKEN_EQUAL  
%left TOKEN_ADD TOKEN_SUB
%left TOKEN_MULT TOKEN_DIV
%right TOKEN_POT
%left TOKEN_DOT

%%
   prog:
      TOKEN_PROGRAM NAME TOKEN_BEGIN decl_block TOKEN_END
   decl_block:
%%

void yyerror( char const* s) {
    std::cerr << "Erro: " << s << "\n";
}